export type RegistryItem = { name: string; group: string; description: string; state: 'ready' | 'connection-required' };

const toolNames = [
  'readFile','writeFile','listFiles','grep','findReplace','renameFile','moveFile','copyFile','deleteFile','appendFile','prependFile','diffFiles','mergeFiles','extractImports','formatCode','lintProject','typecheckProject','validateJson','generateTypes','analyzeCode','reviewArchitecture','reviewSecurity','reviewPerformance','explainError','createComponent','createPage','createApiRoute','createHook','createService','createTest','scaffoldProject','runBuild','runTests','inspectPackage','installPackage','removePackage','upgradePackage','lockfileAudit','getProjectInfo','getEnvironmentInfo','getProjectStructure','searchWorkspace','summarizeFile','summarizeProject','writeDocumentation','generateReadme','generateChangelog','createIssueDraft','createPullRequestDraft','branchPlan','commitPlan','gitStatus','gitDiff','gitLog','compareBranches','githubListRepos','githubReadFile','githubListIssues','githubListPullRequests','githubCreateIssue','githubCreatePullRequestDraft','webFetch','extractWebPage','searchWeb','parseSitemap','checkLinks','checkHeaders','checkAccessibility','analyzeImage','extractTextFromImage','analyzePdf','parseCsv','summarizeDataset','validateSchema','calculate','convertTimestamp','hashText','encodeText','decodeText','testRegex','countStats','sortLines','minifyJson','formatMarkdown','generateUuid','generatePassword','saveMemory','recallMemory','forgetMemory','summarizeMemory','saveReminder','listReminders','recordTask','listTaskHistory','healthCheck','scanErrors','classifyError','createRepairPlan','runSafeRepair','circuitStatus','resetCircuit','agentHandoff','parallelPlan','delegateResearch','selectModel','estimateContext','exportConversation','importConversation','newWorkspace','archiveChat','restoreChat','setPreference','auditSession','clearLocalData','createConnector','testConnector','listConnectors','disconnectConnector','deploymentCheck','buildArtifact','deploymentPlan','releaseNotes','rollbackPlan','privacyAudit','dependencyAudit','secretScan','supplyChainScan','incidentReport','statusReport','decisionLog','userFeedback','voiceTranscript','fileAnalysis','workspaceSearch','knowledgeCapture','knowledgeQuery','taskQueue','scheduleDraft','webhookDraft','oauthStatus','accessReview','permissionReport','safeModeToggle','capabilityReport','agentProfile','skillLibrary','skillVersion','selfEvaluation','improvementPlan',
];

export const tools: RegistryItem[] = toolNames.map((name, index) => ({
  name,
  group: index < 32 ? 'Build & Code' : index < 58 ? 'Git & Projekte' : index < 78 ? 'Web & Daten' : index < 104 ? 'Memory & Agenten' : 'Governance & Betrieb',
  description: 'Registry-Eintrag; Ausführung erfolgt nur über eine konfigurierte, sichere Integration.',
  state: 'ready',
}));

export const connectors: RegistryItem[] = [
  ['GitHub','Code & Repositories'],['Google Drive','Dateien & Suche'],['Google Calendar','Termine'],['Gmail','E-Mail'],['Slack','Team-Kommunikation'],['Notion','Wissensbasis'],['Linear','Projektmanagement'],['Sentry','Fehler & Monitoring'],['Jira','Tickets'],['Confluence','Dokumentation'],['Microsoft 365','Office & Dateien'],['Outlook','E-Mail'],['Teams','Team-Kommunikation'],['Dropbox','Dateien'],['OneDrive','Dateien'],['Airtable','Daten'],['Supabase','Datenbank'],['Postgres','Datenbank'],['Neon','Datenbank'],['Upstash Redis','Rate Limit & Cache'],['Vercel','Deployment'],['Cloudflare','Edge & DNS'],['AWS','Cloud'],['Figma','Design'],['HubSpot','CRM'],['Salesforce','CRM'],['Shopify','Commerce'],['Stripe','Finanzen'],['Telegram','Messaging'],['Discord','Community'],
].map(([name, group]) => ({ name, group, description: 'OAuth/API-Verbindung wird serverseitig konfiguriert.', state: 'connection-required' }));
